### ISSUE TITLE
Design QA

### ISSUE THREAD

**Issue by kvanderslice** [fiftyandfiftyorg/unitedwaymilehigh#78]

**Comment by wstecklair** [comment]
MOBILE DESIGN QA

All in all, really looks great. Just a few things (like you mentioned) that need some attention. Let us know if you need design support on anything or on any decision. Glad to collaborate as needed. Rockin it!

[ ] Logo - Funny thing, the Logo bumps up into hello bar on my phone and the nav icon is just fine. But on yours the logo is fine and the nav icon bumps up into the bar.

[ ] Title is missing or hidden...

![img_1084](https://user-images.githubusercontent.com/28412045/39552134-c907fe04-4e1c-11e8-9dda-0db569ffdcca.jpg)


[ ] I mentioned it to stutts, so it's more of a design thing, but we should add some sort of indicators or something to indicate it is a rotator/swipeable. Dots, arrows, whatev helps... otherwise it feels a little strange. (Update on all pages this UI piece is used)...

![img_1085](https://user-images.githubusercontent.com/28412045/39552184-036c9bf4-4e1d-11e8-8dc6-302ce074fe38.jpg)

[ ] Add padding between each photo square (like you mentioned). (Update on all pages this UI piece is used)...

![img_1086](https://user-images.githubusercontent.com/28412045/39552256-425abf9e-4e1d-11e8-81ad-f475917b7749.jpg)


[ ] Footer - links run down into the very bottom of the footer. Also, is the Fifty link clickable? If so it's not working on mobile.

![img_1087](https://user-images.githubusercontent.com/28412045/39552289-6ac5bc40-4e1d-11e8-94f8-c0490a19c066.jpg)

**Comment by stutts** [comment]
Stutts - Desktop QA

- [ ] Looks like a gap is appearing between the header and the light grey background of the following section when the screen is set to certain smaller widths.
![image](https://user-images.githubusercontent.com/14879336/39551755-28dfdfa6-4e1b-11e8-96ec-6032a775d4b1.png)

- [ ] Let's nix the drop shadow on the 211 bar. I think the difference between the light grey and the white should offer enough contrast.
![image](https://user-images.githubusercontent.com/14879336/39551842-8c569354-4e1b-11e8-9d73-5edca865a794.png)

- [ ] Can we slightly decrease the space between the lines in the hamburger nav? Maybe just by a few pixels. I think it would look better if they were a little closer together.
![image](https://user-images.githubusercontent.com/14879336/39551900-c9dc3a8a-4e1b-11e8-96ee-addc5efa69da.png)

- [ ] I talked with Weston and I think we need to add slide number indicator dots below these cards. I'd like users to be able click through on their own (especially if there are several promos. So I'll update the designs and let you know when they're done.
![image](https://user-images.githubusercontent.com/14879336/39552015-4857d748-4e1c-11e8-8b61-4dfc4085b63a.png)

- [ ] Can we use the same hover effect for the blue buttons in the footer that we use on the other blue buttons (slight darkening as opposed to changing transparency)? I think it would be good to have a consistent hover for each color button.
![image](https://user-images.githubusercontent.com/14879336/39552154-e1c105a8-4e1c-11e8-921c-60737dafea85.png)

- [ ] I think we're going to have to switch to the broken out design of the nav that's in the ui kit since they added several more nav items (about us, for companies...)
![image](https://user-images.githubusercontent.com/14879336/39552458-3508b64c-4e1e-11e8-90a2-81bd835fc55a.png)

- [ ] Let's switch to white for the search bar. The light grey on light grey feels a little weird.
![image](https://user-images.githubusercontent.com/14879336/39552505-5d0d8d98-4e1e-11e8-9b23-707fccf9fd07.png)

- [ ] For the 4 block rotator let's change the "Learn More's" to all caps like the other buttons. And can we center the arrows vertically with the type? And add some horizontal space (15 px) between them? (in the screen shot the PSD is on the left) And then on hover let's nix the arrows.
![image](https://user-images.githubusercontent.com/14879336/39552646-efae9ba6-4e1e-11e8-96dd-de79f0dc7fac.png)

- [ ] In the nav bar, can we left align the 211 text with the logo and right align the "x" with the hamburger nav?
![image](https://user-images.githubusercontent.com/14879336/39552976-69ef4d6a-4e20-11e8-94e0-7876aef98a69.png)

- [ ] Can we add a hard return under the titles in the promo cards on the homepage? (PSD on the left)
![image](https://user-images.githubusercontent.com/14879336/39553047-a104b362-4e20-11e8-8ec9-a9089095f01f.png)

- [ ] Can we lighten the overlay a little on the Get Involved page?
![image](https://user-images.githubusercontent.com/14879336/39553130-fc4dc5c4-4e20-11e8-8eda-da020f9ebe3a.png)

- [ ] Let's recommend to them to add a subtitle on the blog page. You were right that it looks pretty light without one.
![image](https://user-images.githubusercontent.com/14879336/39553171-2c788842-4e21-11e8-89a2-11d5d5562721.png)

- [ ] Let's bump up this intro on the Economic opportunity page to 21px with 32px of line spacing. 
![image](https://user-images.githubusercontent.com/14879336/39553254-8a893b0c-4e21-11e8-8ff4-6f5dd714c5d2.png)

- [ ] After I closed the 211 bar the Search turned to white.
![image](https://user-images.githubusercontent.com/14879336/39553296-cda0171c-4e21-11e8-85c5-eb4cae4fe39b.png)


I think that's all I've got. Nice job dude!!
